### ISSUE TITLE
New ML library - NNS

### ISSUE THREAD

**Issue by alphabotrobertospadim** [Kaggle/docker-rcran#51]
Hi Folks, could be possible include NNS package? I'm trying to use it at Optiver Competition but I can only submit without using internet, but I need Internet to install NNS

my code to install at kaggle:

```
install.packages("NNS"); 
library(NNS)
```

**Comment by rspadim** [comment]
ops wrong user, watching here with the right one

**Comment by Philmod** [comment]
It seems like it's installed: https://github.com/Kaggle/docker-rcran/blob/main/packages_users#L192
