### ISSUE TITLE
sprtt package is missing

### ISSUE THREAD

**Issue by aliaamiri** [Kaggle/docker-rcran#58]
Recently, I tried to load `sprtt`  r package in Kaggle but it was not successful. It is not included in the list of packages in this repo too.
What is the protocol to make a package available in Kaggle?
Best Regards

`sprtt` package links:

https://cran.r-project.org/web/packages/sprtt/index.html 
https://github.com/MeikeSteinhilber/sprtt

**Comment by Philmod** [comment]
Hi @aliaamiri,

We usually install packages that are used on Kaggle.

In the meantime, you could install the missing package in your notebook: `install.packages('sprtt')`

Best,
Philippe
